#!/bin/bash
# GitHub Pages 手動配置腳本
# 如果 GitHub Actions 自動配置失敗，可以運行此腳本手動設置

echo "🚀 GitHub Pages 手動配置指南"
echo ""
echo "請手動完成以下步驟："
echo ""
echo "1️⃣  進入 GitHub 倉庫"
echo "   https://github.com/yourusername/diff-lens"
echo ""
echo "2️⃣  進入 Settings"
echo "   點擊右上角 Settings 按鈕"
echo ""
echo "3️⃣  找到 Pages 設置"
echo "   左側菜單 → Pages（在 Code and automation 下）"
echo ""
echo "4️⃣  配置 GitHub Pages 來源"
echo "   Build and deployment:"
echo "     • Source: Deploy from a branch"
echo "     • Branch: gh-pages"
echo "     • Folder: / (root)"
echo "     • 點擊 Save"
echo ""
echo "5️⃣  等待部署完成"
echo "   • 刷新 Pages 設置頁面"
echo "   • 應該看到藍色的「Your site is live」消息"
echo "   • 對應的 URL 會顯示在該消息旁邊"
echo ""
echo "6️⃣  訪問您的應用"
echo "   https://yourusername.github.io/diff-lens/"
echo ""
echo "⚠️  常見問題："
echo ""
echo "  Q: 為什麼還是 404？"
echo "  A: 確認 gh-pages 分支存在且 Branch 設置正確"
echo ""
echo "  Q: 顯示 'Folder' 選項但無法選擇 '/'？"
echo "  A: 確保已選擇 'Deploy from a branch' 而不是其他源"
echo ""
echo "  Q: 部署後還是 404？"
echo "  A: 等待 5-10 分鐘，GitHub Pages 可能需要時間更新"
